import React from 'react';
import Hero from '../../ui/Hero';
import Section from '../../layout/Section';
import SectionHeader from '../../ui/SectionHeader';
import Card from '../../ui/Card';
import Button from '../../ui/Button';
import {
    ShareIcon,
    CpuChipIcon,
    SparklesIcon,
    UserGroupIcon,
    CodeBracketIcon,
    DocumentTextIcon,
    MagnifyingGlassIcon,
    ShieldCheckIcon
} from '@heroicons/react/24/outline';
import { useSEO } from '../../seo/useSEO';
import ArchitectureDiagram from '../../ui/ArchitectureDiagram';

const capabilities = [
    { name: 'API-First Automation', description: 'Builds resilient automation that interacts with systems at the data layer, not the fragile UI layer, preventing constant breakage.', icon: CodeBracketIcon },
    { name: 'Intelligent Document Processing', description: 'Agents that can read, understand, and extract structured data from unstructured documents like invoices, contracts, and emails.', icon: DocumentTextIcon },
    { name: 'Human-in-the-Loop Workflows', description: 'Design complex workflows that seamlessly escalate exceptions and decisions to the right human expert for approval.', icon: UserGroupIcon },
    { name: 'Process Mining & Discovery', description: 'Use AI to analyze your system logs, creating a data-driven map of your actual business processes to identify the highest-value automation opportunities.', icon: MagnifyingGlassIcon },
    { name: 'Cognitive Agent Orchestration', description: 'Deploy a central "conductor" agent that manages and coordinates fleets of specialized agents to execute complex, multi-system processes.', icon: ShareIcon },
];

const outcomes = [
    { metric: '40-60%', description: 'Reduction in manual processing costs', industry: 'Shared Services' },
    { metric: 'Up to 80%', description: 'Faster process cycle times', industry: 'Finance & Operations' },
    { metric: '99%+ ', description: 'Improvement in data entry and process accuracy', industry: 'All' },
];

const industries = [
    { name: 'Shared Services', description: 'Automating core functions like Finance, HR, and IT to create a hyper-efficient back office.' },
    { name: 'Back Office Operations', description: 'Streamlining complex, document-heavy workflows in banking, insurance, and logistics.' },
    { name: 'Operations & Fulfillment', description: 'Orchestrating order processing, inventory management, and customer service workflows.' },
];

const IntelligentAutomationPage: React.FC = () => {
    useSEO({
        title: 'Intelligent Automation Solutions',
        description: 'Automate complex, end-to-end business operations with AI and a Unified Ontology, moving beyond simple tasks to cognitive workflows.',
        keywords: 'intelligent automation, RPA, process automation, workflow automation, generative AI agents, process mining'
    });

    return (
        <div className="bg-white">
            <Hero
                breadcrumb="SOLUTION: INTELLIGENT AUTOMATION"
                title="From Scripts & Bots to Cognitive Automation."
                subtitle="We move beyond brittle RPA to architect a resilient, intelligent automation capability. Our Cognitive Agents are grounded in your Unified Ontology, allowing them to understand context, handle exceptions, and automate entire end-to-end processes."
            >
                 <div className="mt-10 flex flex-col sm:flex-row justify-center gap-4">
                    <Button to="/contact">Talk to an Architect</Button>
                    <Button to="/platform" primary={false} className="!text-stone !border-stone hover:!bg-stone hover:!text-charcoal">Explore the Platform</Button>
                </div>
            </Hero>

            <Section tone="light">
                <SectionHeader
                    eyebrow="The Challenge"
                    title="The Enterprise Problem: Your 'Army of Bots' is a Liability"
                    description="The initial promise of Robotic Process Automation (RPA) has given way to a painful reality: a sprawling, brittle army of bots that break with every UI change. This 'technical debt' creates a massive maintenance burden, and the exceptions and errors generated by simple bots often kill any potential ROI."
                    align='center'
                    maxWidth='lg'
                />
            </Section>

            <Section tone="soft">
                <SectionHeader
                    eyebrow="Why Traditional Approaches Fail"
                    title="UI-Level Automation is Fundamentally Flawed"
                    description="Traditional RPA operates at the most fragile layer: the user interface. It has no deep understanding of the underlying data or business process. It cannot read unstructured documents, handle process variations, or make judgments. It is a temporary patch, not a scalable solution."
                    align='center'
                    maxWidth='lg'
                />
            </Section>

            <Section tone="light">
                <SectionHeader
                    eyebrow="The Akin Solution"
                    title="Automation Grounded in Context and Intelligence"
                    description="We architect automation that is API-first and ontology-grounded. Our Cognitive Agents interact with your systems at the data layer, making them resilient and scalable. Because they are connected to your Unified Ontology, they understand the context of the data they are working with. This allows them to automate 90% of a complex process, not just 10% of a simple task."
                    align='center'
                    maxWidth='lg'
                />
            </Section>
            
            <Section tone="soft">
                <SectionHeader
                    eyebrow="Core Capabilities"
                    title="What the Intelligent Automation System Does"
                    align="center"
                    maxWidth="lg"
                />
                <div className="mt-12 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8 text-left">
                    {capabilities.map((item) => (
                        <Card key={item.name}>
                             <item.icon className="h-8 w-8 text-electric-blue mb-3" />
                             <h3 className="text-lg font-bold text-charcoal">{item.name}</h3>
                             <p className="mt-1 text-sm text-charcoal-light">{item.description}</p>
                        </Card>
                    ))}
                </div>
            </Section>

            <Section tone="light">
                 <SectionHeader
                    eyebrow="Architecture"
                    title="Powered by the Akin Platform"
                    align="center"
                    maxWidth="lg"
                />
                <ArchitectureDiagram />
                <div className="max-w-4xl mx-auto mt-8 text-center text-charcoal-light">
                    <p>This solution leverages the Akin platform to deliver resilient automation. The **Unified Ontology** provides the business context agents need to act. The **MLOps Engine** builds the models for tasks like document understanding. **Cognitive Agents** execute the workflows. The **Command Center** provides the human-in-the-loop governance for exceptions.</p>
                </div>
            </Section>

            <Section tone="dark">
                <SectionHeader
                    eyebrow="Outcomes"
                    title="Operational Impact That Scales"
                    align="center"
                    maxWidth="lg"
                />
                <div className="mt-12 grid grid-cols-1 sm:grid-cols-3 gap-8">
                    {outcomes.map(item => (
                        <Card key={item.description} className="text-center bg-white/5 border-white/10 text-stone">
                            <p className="text-5xl font-extrabold text-green">{item.metric}</p>
                            <p className="mt-2 font-semibold text-white">{item.description}</p>
                             <p className="mt-1 text-sm text-gray-400">Context: {item.industry}</p>
                        </Card>
                    ))}
                </div>
            </Section>
            
            <Section tone="light">
                <SectionHeader
                    eyebrow="Applicability"
                    title="Where This Applies"
                    description="Intelligent Automation delivers transformative efficiency to any function burdened by manual, repetitive, and high-volume processes."
                    align='center'
                    maxWidth='lg'
                />
                 <div className="mt-12 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
                    {industries.map(industry => (
                        <Card key={industry.name}>
                            <h4 className="font-bold text-charcoal">{industry.name}</h4>
                            <p className="text-sm text-charcoal-light mt-1">{industry.description}</p>
                        </Card>
                    ))}
                </div>
            </Section>
            
            <Section tone="soft">
                <SectionHeader
                    eyebrow="Why Akin"
                    title="Our Differentiation: Architectural DNA"
                    align='center'
                    maxWidth='lg'
                />
                <div className="mt-8 max-w-4xl mx-auto grid md:grid-cols-3 gap-8 text-center">
                    <div className="p-4">
                        <CpuChipIcon className="h-10 w-10 mx-auto text-electric-blue" />
                        <h4 className="mt-2 font-bold">Ontology-Grounded</h4>
                        <p className="text-sm text-charcoal-light">Our agents understand your business context, enabling them to handle complex exceptions.</p>
                    </div>
                    <div className="p-4">
                        <SparklesIcon className="h-10 w-10 mx-auto text-electric-blue" />
                        <h4 className="mt-2 font-bold">AI-Powered, Not Just Rule-Based</h4>
                        <p className="text-sm text-charcoal-light">Our agents can read documents and make judgments, automating end-to-end processes.</p>
                    </div>
                     <div className="p-4">
                        <ShieldCheckIcon className="h-10 w-10 mx-auto text-electric-blue" />
                        <h4 className="mt-2 font-bold">Enterprise-Grade Governance</h4>
                        <p className="text-sm text-charcoal-light">We build fully auditable systems with robust human-in-the-loop controls from day one.</p>
                    </div>
                </div>
            </Section>

            <Section tone="dark" align="center">
                <SectionHeader
                    eyebrow="CTA"
                    title="Architect Your Cognitive Automation Capability."
                    description="Let's identify the high-value, end-to-end processes that are ready for intelligent, resilient automation."
                    align="center"
                    maxWidth="md"
                />
                <div className="mt-8">
                    <Button to="/contact">Talk to an Architect</Button>
                </div>
            </Section>
        </div>
    );
};

export default IntelligentAutomationPage;
